language: objective-c
xcode_project: testCI.xcodeproj # path to your xcodeproj folder
xcode_scheme: testCI
osx_image: xcode10.1
xcode_destination: platform:iOS Simulator, iPad (6th generation), OS:12.1